-- =========================================================================
-- V3__seed_all_prabhatech_portfolio.sql : Canonical 12 PrabhaTech Projects
-- =========================================================================

-- Clean up older initial placeholder demo seeds if needed or upsert with authentic data
DELETE FROM case_studies WHERE slug IN ('cr2-digital-banking-platform', 'myeva-wealthtech-ai-financial-coach', 'b2b-corporate-treasury-platform');

INSERT INTO case_studies (
    slug, title, subtitle, client_name, category, 
    hero_image_url, thumbnail_url, summary, 
    challenge, solution, results, awards, metrics, tags, 
    featured, display_order, is_published
)
VALUES
(
    'super-app-all-in-one',
    'Super App All-in-One Enterprise Platform',
    'A unified mobile and web application integrating multiple services, business operations, and customer engagement',
    'Digital Holding Group',
    'Enterprise Solutions',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    'A unified mobile and web application integrating multiple services, business operations, and customer engagement in one seamless platform.',
    'Fragmentation across isolated consumer apps leading to high user acquisition costs and friction.',
    'Designed and developed a scalable micro-frontend and modular mobile super-app architecture.',
    'Achieved over 2.5 million active users with 99.99% transaction uptime across retail, lifestyle, and financial services.',
    '["Enterprise App of the Year", "GCC Digital Disruption Winner"]'::jsonb,
    '[{"label": "2.5M+", "description": "Active Users"}, {"label": "99.99%", "description": "Uptime"}, {"label": "4.8 ★", "description": "App Store Rating"}]'::jsonb,
    '["Super App", "Mobile", "Enterprise Platform", "Cross-Platform"]'::jsonb,
    true,
    1,
    true
),
(
    'ai-fleet-management',
    'AI Fleet Management & Telematics',
    'Smart platform for heavy equipment sales, rental maintenance, and tracking with AI-powered fleet operations',
    'Leading Logistics Enterprise',
    'Industrial & IoT',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    'Smart platform for heavy equipment sales, rental maintenance, and tracking with AI-powered fleet operations and analytics.',
    'Unplanned equipment breakdowns and inefficient dispatch routing incurring millions in annual operational losses.',
    'Integrated IoT telematics edge devices with predictive machine learning algorithms for predictive maintenance alerts.',
    'Eliminated 42% of unplanned machinery downtime and delivered SAR 1.2M in annual fuel cost savings across 3,200 vehicles.',
    '["Industrial IoT Gold Award"]'::jsonb,
    '[{"label": "-42%", "description": "Equipment Downtime"}, {"label": "3,200+", "description": "Active Vehicles"}, {"label": "SAR 1.2M", "description": "Annual Fuel Savings"}]'::jsonb,
    '["Fleet Telematics", "Industrial IoT", "Predictive AI", "Logistics"]'::jsonb,
    true,
    2,
    true
),
(
    'bigauction-portal',
    'BigAuction Digital Auction Exchange',
    'A digital auction platform for heavy equipment, vehicles, and industrial assets with live bidding and global reach',
    'Industrial Asset Auctions',
    'Platforms & Marketplaces',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    'A digital auction platform for heavy equipment, vehicles, and industrial assets with live bidding, secure payments, and global reach.',
    'Physical auction floor limitations restricting bidder participation and slowing transaction settlement.',
    'Built ultra-low latency WebSocket bidding engine with escrow integration and automated catalog verification.',
    'Successfully processed over SAR 450M in gross auction volume with sub-80ms bidding latency across 14 countries.',
    '["Digital Marketplace Innovation Winner"]'::jsonb,
    '[{"label": "SAR 450M+", "description": "Gross Volume"}, {"label": "<80ms", "description": "Real-Time Bidding"}, {"label": "14 Countries", "description": "Active Bidders"}]'::jsonb,
    '["Digital Auction", "Real-Time Bidding", "WebSockets", "Industrial Assets"]'::jsonb,
    true,
    3,
    true
),
(
    'grecha-ai-hrms',
    'Grecha.ai Enterprise AI HRMS',
    'All-in-one HRMS with attendance, payroll, leave, performance, recruitment, and workforce management',
    'Grecha Global Group',
    'Enterprise Solutions',
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    'All-in-one HRMS with attendance, payroll, leave, performance, recruitment, and workforce management for modern enterprises.',
    'Disparate HR tools creating payroll processing bottlenecks and human compliance errors.',
    'Engineered an enterprise AI-assisted workforce suite with automated compliance checks and biometric synchronization.',
    'Empowered 15,000+ enterprise employees with zero payroll errors and cut monthly processing time by 75%.',
    '["Enterprise HR SaaS Award"]'::jsonb,
    '[{"label": "15,000+", "description": "Employees Managed"}, {"label": "100%", "description": "Automated Payroll"}, {"label": "-75%", "description": "Processing Time"}]'::jsonb,
    '["HRMS", "Workforce AI", "Payroll", "Enterprise HR"]'::jsonb,
    true,
    4,
    true
),
(
    'ai-camera-analytics',
    'AI Video Analytics & Crowd Intelligence',
    'Real-time video analytics for malls and commercial spaces with crowd analysis, behavior detection, and smart monitoring',
    'Commercial Centers & Retail Malls',
    'AI & Analytics',
    'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80',
    'Real-time video analytics for malls and commercial spaces with crowd analysis, behavior detection, and smart monitoring.',
    'Security teams overwhelmed by hundreds of manual camera monitors without real-time threat or bottleneck detection.',
    'Deployed high-throughput computer vision models for heatmapping, anomaly classification, and queue management.',
    'Achieved 99.4% detection precision with sub-second alert latency across 500+ commercial CCTV streams.',
    '["Smart Retail AI Award"]'::jsonb,
    '[{"label": "99.4%", "description": "Detection Precision"}, {"label": "<1s", "description": "Anomaly Alert"}, {"label": "500+", "description": "Connected Streams"}]'::jsonb,
    '["Computer Vision", "Crowd Analytics", "AI Security", "Retail Intelligence"]'::jsonb,
    true,
    5,
    true
),
(
    'bems-smart-buildings',
    'BEMS Intelligent Building Energy Management',
    'AI-powered Building Energy Management System for HVAC, electrical, and facilities with real-time monitoring and optimization',
    'GCC Real Estate Consortium',
    'Smart Solutions',
    '/assets/images/glass-office-building.jpeg',
    '/assets/images/glass-office-building.jpeg',
    'AI-powered Building Energy Management System for HVAC, electrical, and facilities with real-time monitoring, analytics, and energy optimization.',
    'Skyrocketing power cooling costs across commercial towers without real-time occupancy-aware throttling.',
    'Engineered an autonomous building energy management system integrating BACnet/Modbus IoT gateways with predictive load balancing.',
    'Achieved 125.4 MWh monthly energy savings and SAR 36,820 monthly utility reductions per facility.',
    '["Green Building Tech of the Year"]'::jsonb,
    '[{"label": "125.4 MWh", "description": "Monthly Energy Saved"}, {"label": "SAR 36,820", "description": "Monthly Cost Reduction"}, {"label": "99.8%", "description": "System Uptime"}]'::jsonb,
    '["Smart Buildings", "BEMS", "Energy AI", "IoT Facilities"]'::jsonb,
    true,
    6,
    true
),
(
    'insurance-crm-portal',
    'Insurance Broker CRM & Policy Hub',
    'Complete CRM for insurance brokers and agents with lead management, policy tracking, reminders, and meeting scheduling',
    'Regional Insurance Alliance',
    'Enterprise Solutions',
    'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    'Complete CRM for insurance brokers and agents with lead management, policy tracking, reminders, and meeting scheduling.',
    'Low policy renewal rates due to manual paper tracking and uncoordinated broker schedules.',
    'Built an end-to-end policy lifecycle management portal with automated WhatsApp/SMS renewal notifications.',
    'Boosted policy renewal retention by 38% and supported over 10,000 active insurance accounts.',
    '["Fintech Portal Excellence"]'::jsonb,
    '[{"label": "+38%", "description": "Renewal Retention"}, {"label": "10,000+", "description": "Active Policies"}, {"label": "3x", "description": "Broker Productivity"}]'::jsonb,
    '["InsurTech", "Broker CRM", "Policy Management", "Enterprise"]'::jsonb,
    true,
    7,
    true
),
(
    'wefyx-it-platform',
    'Wefyx.pro Managed IT Support & Rental',
    'One-stop platform for IT support, equipment rental, managed services, AMC, and on-site engineer booking',
    'Wefyx Global',
    'IT Services',
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    'One-stop platform for IT support, equipment rental, managed services, AMC, and on-site engineer booking for businesses and individuals.',
    'Delays in enterprise hardware provisioning and fragmented technician support across metropolitan hubs.',
    'Architected an on-demand IT service marketplace with real-time engineer geotracking and automated SLA auditing.',
    'Delivered 24/7 SLA guaranteed IT support with an average on-site technician dispatch time under 15 minutes.',
    '["IT Service Platform of the Year"]'::jsonb,
    '[{"label": "24/7", "description": "SLA Guaranteed"}, {"label": "<15 min", "description": "Dispatch Time"}, {"label": "99.1%", "description": "First-Time Resolution"}]'::jsonb,
    '["IT Support", "Managed Services", "Hardware Rental", "Field Services"]'::jsonb,
    true,
    8,
    true
),
(
    'smart-gate-cloud',
    'Smart Gate Cloud Access & Security',
    'Cloud-based access control and gate management system with real-time monitoring, visitor management, and secure entry',
    'Corporate Campuses & Communities',
    'Smart Solutions',
    'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    'Cloud-based access control and gate management system with real-time monitoring, visitor management, and secure entry solutions.',
    'Traffic queues and unauthorized access vulnerabilities at corporate entry gates and residential compounds.',
    'Deployed ANPR license plate recognition with QR pass issuance and cloud gate barrier telemetry.',
    'Zero-wait automated entry for 50,000+ registered vehicles with 100% cloud-audited access logs.',
    '["Security Innovation Award"]'::jsonb,
    '[{"label": "Zero-Wait", "description": "ANPR Entry"}, {"label": "50,000+", "description": "Registered Vehicles"}, {"label": "100%", "description": "Audit Trail"}]'::jsonb,
    '["Smart Gate", "ANPR", "Cloud Access", "Security IoT"]'::jsonb,
    true,
    9,
    true
),
(
    'vertical-farming-iot',
    'Vertical Farming Controlled Climate IoT',
    'IoT and AI-based smart farming system for controlled environment agriculture, increasing yield and resource efficiency',
    'Sustainable Agriculture Initiative',
    'Industrial & IoT',
    'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=800&q=80',
    'IoT and AI-based smart farming system for controlled environment agriculture, increasing yield and resource efficiency.',
    'Severe climate conditions and scarce fresh water challenging traditional GCC agriculture.',
    'Engineered hydroponic sensor telemetry and nutrient dosage controllers with machine learning harvest modeling.',
    'Conserved 95% fresh water compared to open-field farming and elevated crop harvest yields by 35%.',
    '["AgriTech Sustainability Winner"]'::jsonb,
    '[{"label": "95%", "description": "Water Conserved"}, {"label": "+35%", "description": "Crop Yield"}, {"label": "Zero", "description": "Pesticides Used"}]'::jsonb,
    '["AgriTech", "Vertical Farming", "Hydroponics IoT", "Automation"]'::jsonb,
    true,
    10,
    true
),
(
    'rewards-portal',
    'Enterprise Loyalty & Rewards Portal',
    'Enterprise rewards and loyalty platform where companies and banks can purchase rewards for customers and direct users',
    'Banking & Retail Partners',
    'Platforms & Marketplaces',
    'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&q=80',
    'Enterprise rewards and loyalty platform where companies and banks can purchase rewards for their customers, and users can also buy directly.',
    'Complex reward redemption across diverse retail partners causing points expiration and poor brand engagement.',
    'Built an omni-partner digital rewards exchange with instantaneous gift voucher generation and API POS settlement.',
    'Issued over 4.2 million digital gift vouchers with instant merchant redemption across 800+ retail brands.',
    '["Fintech Loyalty Award"]'::jsonb,
    '[{"label": "4.2M+", "description": "Vouchers Issued"}, {"label": "800+", "description": "Retail Brands"}, {"label": "Instant", "description": "POS Settlement"}]'::jsonb,
    '["Loyalty & Rewards", "Gift Cards", "Fintech API", "Merchant Network"]'::jsonb,
    true,
    11,
    true
),
(
    'blink-financial-pay',
    'Blink Financial Pay App',
    'Secure and modern payment application for seamless transactions, wallet services, and financial management',
    'Blink Financial Services',
    'Mobile Applications',
    'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    'Secure and modern payment application for seamless transactions, wallet services, and financial management for individuals and businesses.',
    'Clunky mobile payment checkouts with high failure rates during peak shopping hours.',
    'Engineered high-concurrency microservices with biometric 1-tap checkout and tokenized PCI-DSS compliance.',
    'Attained PCI-DSS Level 1 certification with instantaneous peer-to-peer settlement and 99.98% authorization success.',
    '["Best Mobile Payment UX"]'::jsonb,
    '[{"label": "PCI-DSS", "description": "Level 1 Certified"}, {"label": "Instant", "description": "P2P Settlement"}, {"label": "99.98%", "description": "Success Rate"}]'::jsonb,
    '["Mobile Payments", "Digital Wallet", "Fintech", "iOS & Android"]'::jsonb,
    true,
    12,
    true
)
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    client_name = EXCLUDED.client_name,
    category = EXCLUDED.category,
    hero_image_url = EXCLUDED.hero_image_url,
    thumbnail_url = EXCLUDED.thumbnail_url,
    summary = EXCLUDED.summary,
    challenge = EXCLUDED.challenge,
    solution = EXCLUDED.solution,
    results = EXCLUDED.results,
    awards = EXCLUDED.awards,
    metrics = EXCLUDED.metrics,
    tags = EXCLUDED.tags,
    featured = EXCLUDED.featured,
    display_order = EXCLUDED.display_order,
    is_published = EXCLUDED.is_published,
    updated_at = CURRENT_TIMESTAMP;
